/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: planner.proto3 */

#ifndef PROTOBUF_C_planner_2eproto3__INCLUDED
#define PROTOBUF_C_planner_2eproto3__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Planner__Plan Planner__Plan;
typedef struct Planner__Planner Planner__Planner;
typedef struct Planner__Planner__ArenaProfile Planner__Planner__ArenaProfile;


/* --- enums --- */


/* --- messages --- */

struct  Planner__Plan
{
  ProtobufCMessage base;
  char *name;
  int32_t start_idx;
  int32_t size;
  int32_t type;
  int32_t ndata;
  size_t n_dims;
  int32_t *dims;
};
#define PLANNER__PLAN__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planner__plan__descriptor) \
    , (char *)protobuf_c_empty_string, 0, 0, 0, 0, 0,NULL }


struct  Planner__Planner__ArenaProfile
{
  ProtobufCMessage base;
  int32_t max_ntensors;
  int32_t max_bytes;
};
#define PLANNER__PLANNER__ARENA_PROFILE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planner__planner__arena_profile__descriptor) \
    , 0, 0 }


struct  Planner__Planner
{
  ProtobufCMessage base;
  Planner__Planner__ArenaProfile *arena;
  size_t n_plans;
  Planner__Plan **plans;
};
#define PLANNER__PLANNER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planner__planner__descriptor) \
    , NULL, 0,NULL }


/* Planner__Plan methods */
void   planner__plan__init
                     (Planner__Plan         *message);
size_t planner__plan__get_packed_size
                     (const Planner__Plan   *message);
size_t planner__plan__pack
                     (const Planner__Plan   *message,
                      uint8_t             *out);
size_t planner__plan__pack_to_buffer
                     (const Planner__Plan   *message,
                      ProtobufCBuffer     *buffer);
Planner__Plan *
       planner__plan__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planner__plan__free_unpacked
                     (Planner__Plan *message,
                      ProtobufCAllocator *allocator);
/* Planner__Planner__ArenaProfile methods */
void   planner__planner__arena_profile__init
                     (Planner__Planner__ArenaProfile         *message);
/* Planner__Planner methods */
void   planner__planner__init
                     (Planner__Planner         *message);
size_t planner__planner__get_packed_size
                     (const Planner__Planner   *message);
size_t planner__planner__pack
                     (const Planner__Planner   *message,
                      uint8_t             *out);
size_t planner__planner__pack_to_buffer
                     (const Planner__Planner   *message,
                      ProtobufCBuffer     *buffer);
Planner__Planner *
       planner__planner__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planner__planner__free_unpacked
                     (Planner__Planner *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Planner__Plan_Closure)
                 (const Planner__Plan *message,
                  void *closure_data);
typedef void (*Planner__Planner__ArenaProfile_Closure)
                 (const Planner__Planner__ArenaProfile *message,
                  void *closure_data);
typedef void (*Planner__Planner_Closure)
                 (const Planner__Planner *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor planner__plan__descriptor;
extern const ProtobufCMessageDescriptor planner__planner__descriptor;
extern const ProtobufCMessageDescriptor planner__planner__arena_profile__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_planner_2eproto3__INCLUDED */
