/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: planner.proto3 */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "planner.proto3.pb-c.h"
void   planner__plan__init
                     (Planner__Plan         *message)
{
  static const Planner__Plan init_value = PLANNER__PLAN__INIT;
  *message = init_value;
}
size_t planner__plan__get_packed_size
                     (const Planner__Plan *message)
{
  assert(message->base.descriptor == &planner__plan__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planner__plan__pack
                     (const Planner__Plan *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planner__plan__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planner__plan__pack_to_buffer
                     (const Planner__Plan *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planner__plan__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planner__Plan *
       planner__plan__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planner__Plan *)
     protobuf_c_message_unpack (&planner__plan__descriptor,
                                allocator, len, data);
}
void   planner__plan__free_unpacked
                     (Planner__Plan *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planner__plan__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planner__planner__arena_profile__init
                     (Planner__Planner__ArenaProfile         *message)
{
  static const Planner__Planner__ArenaProfile init_value = PLANNER__PLANNER__ARENA_PROFILE__INIT;
  *message = init_value;
}
void   planner__planner__init
                     (Planner__Planner         *message)
{
  static const Planner__Planner init_value = PLANNER__PLANNER__INIT;
  *message = init_value;
}
size_t planner__planner__get_packed_size
                     (const Planner__Planner *message)
{
  assert(message->base.descriptor == &planner__planner__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planner__planner__pack
                     (const Planner__Planner *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planner__planner__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planner__planner__pack_to_buffer
                     (const Planner__Planner *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planner__planner__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planner__Planner *
       planner__planner__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planner__Planner *)
     protobuf_c_message_unpack (&planner__planner__descriptor,
                                allocator, len, data);
}
void   planner__planner__free_unpacked
                     (Planner__Planner *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planner__planner__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor planner__plan__field_descriptors[6] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Planner__Plan, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_idx",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Planner__Plan, start_idx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Planner__Plan, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Planner__Plan, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ndata",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Planner__Plan, ndata),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dims",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Planner__Plan, n_dims),
    offsetof(Planner__Plan, dims),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned planner__plan__field_indices_by_name[] = {
  5,   /* field[5] = dims */
  0,   /* field[0] = name */
  4,   /* field[4] = ndata */
  2,   /* field[2] = size */
  1,   /* field[1] = start_idx */
  3,   /* field[3] = type */
};
static const ProtobufCIntRange planner__plan__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor planner__plan__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planner.Plan",
  "Plan",
  "Planner__Plan",
  "planner",
  sizeof(Planner__Plan),
  6,
  planner__plan__field_descriptors,
  planner__plan__field_indices_by_name,
  1,  planner__plan__number_ranges,
  (ProtobufCMessageInit) planner__plan__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor planner__planner__arena_profile__field_descriptors[2] =
{
  {
    "max_ntensors",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Planner__Planner__ArenaProfile, max_ntensors),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_bytes",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Planner__Planner__ArenaProfile, max_bytes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned planner__planner__arena_profile__field_indices_by_name[] = {
  1,   /* field[1] = max_bytes */
  0,   /* field[0] = max_ntensors */
};
static const ProtobufCIntRange planner__planner__arena_profile__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor planner__planner__arena_profile__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planner.Planner.ArenaProfile",
  "ArenaProfile",
  "Planner__Planner__ArenaProfile",
  "planner",
  sizeof(Planner__Planner__ArenaProfile),
  2,
  planner__planner__arena_profile__field_descriptors,
  planner__planner__arena_profile__field_indices_by_name,
  1,  planner__planner__arena_profile__number_ranges,
  (ProtobufCMessageInit) planner__planner__arena_profile__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor planner__planner__field_descriptors[2] =
{
  {
    "arena",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Planner__Planner, arena),
    &planner__planner__arena_profile__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "plans",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Planner__Planner, n_plans),
    offsetof(Planner__Planner, plans),
    &planner__plan__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned planner__planner__field_indices_by_name[] = {
  0,   /* field[0] = arena */
  1,   /* field[1] = plans */
};
static const ProtobufCIntRange planner__planner__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor planner__planner__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planner.Planner",
  "Planner",
  "Planner__Planner",
  "planner",
  sizeof(Planner__Planner),
  2,
  planner__planner__field_descriptors,
  planner__planner__field_indices_by_name,
  1,  planner__planner__number_ranges,
  (ProtobufCMessageInit) planner__planner__init,
  NULL,NULL,NULL    /* reserved[123] */
};
