# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: planner.proto3

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='planner.proto3',
  package='planner',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0eplanner.proto3\x12\x07planner\"`\n\x04Plan\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tstart_idx\x18\x02 \x01(\x05\x12\x0c\n\x04size\x18\x03 \x01(\x05\x12\x0c\n\x04type\x18\x04 \x01(\x05\x12\r\n\x05ndata\x18\x05 \x01(\x05\x12\x0c\n\x04\x64ims\x18\x06 \x03(\x05\"\x8e\x01\n\x07Planner\x12,\n\x05\x61rena\x18\x01 \x01(\x0b\x32\x1d.planner.Planner.ArenaProfile\x12\x1c\n\x05plans\x18\x02 \x03(\x0b\x32\r.planner.Plan\x1a\x37\n\x0c\x41renaProfile\x12\x14\n\x0cmax_ntensors\x18\x01 \x01(\x05\x12\x11\n\tmax_bytes\x18\x02 \x01(\x05\x62\x06proto3')
)




_PLAN = _descriptor.Descriptor(
  name='Plan',
  full_name='planner.Plan',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='planner.Plan.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_idx', full_name='planner.Plan.start_idx', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='planner.Plan.size', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='planner.Plan.type', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ndata', full_name='planner.Plan.ndata', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dims', full_name='planner.Plan.dims', index=5,
      number=6, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=123,
)


_PLANNER_ARENAPROFILE = _descriptor.Descriptor(
  name='ArenaProfile',
  full_name='planner.Planner.ArenaProfile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='max_ntensors', full_name='planner.Planner.ArenaProfile.max_ntensors', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_bytes', full_name='planner.Planner.ArenaProfile.max_bytes', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=268,
)

_PLANNER = _descriptor.Descriptor(
  name='Planner',
  full_name='planner.Planner',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='arena', full_name='planner.Planner.arena', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='plans', full_name='planner.Planner.plans', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PLANNER_ARENAPROFILE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=268,
)

_PLANNER_ARENAPROFILE.containing_type = _PLANNER
_PLANNER.fields_by_name['arena'].message_type = _PLANNER_ARENAPROFILE
_PLANNER.fields_by_name['plans'].message_type = _PLAN
DESCRIPTOR.message_types_by_name['Plan'] = _PLAN
DESCRIPTOR.message_types_by_name['Planner'] = _PLANNER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Plan = _reflection.GeneratedProtocolMessageType('Plan', (_message.Message,), dict(
  DESCRIPTOR = _PLAN,
  __module__ = 'planner.proto3_pb2'
  # @@protoc_insertion_point(class_scope:planner.Plan)
  ))
_sym_db.RegisterMessage(Plan)

Planner = _reflection.GeneratedProtocolMessageType('Planner', (_message.Message,), dict(

  ArenaProfile = _reflection.GeneratedProtocolMessageType('ArenaProfile', (_message.Message,), dict(
    DESCRIPTOR = _PLANNER_ARENAPROFILE,
    __module__ = 'planner.proto3_pb2'
    # @@protoc_insertion_point(class_scope:planner.Planner.ArenaProfile)
    ))
  ,
  DESCRIPTOR = _PLANNER,
  __module__ = 'planner.proto3_pb2'
  # @@protoc_insertion_point(class_scope:planner.Planner)
  ))
_sym_db.RegisterMessage(Planner)
_sym_db.RegisterMessage(Planner.ArenaProfile)


# @@protoc_insertion_point(module_scope)
